services:
  database:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    image: node:18-alpine
    build:
      context: ./dockerized-node-app
      dockerfile: Dockerfile
      target: development
    container_name: node-app
    environment:
      - MONGODB_URI=mongodb://database:27017/
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./dockerized-node-app:/app
      - /app/node_modules
    expose:
      - "8080"
    networks:
      - app-network
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.5'

  frontend:
    build:
      context: ./dockerized-react-app
      dockerfile: Dockerfile
      target: development
    container_name: react-app
    volumes:
      - ./dockerized-react-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: npm run dev
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
