# Use the alpine node LTS Image  
FROM node:18-alpine 

# Create a working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .

# Install Dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# expose 8080 port
EXPOSE 8080

# Run the application
CMD ["node", "index.js"]

